# Generated by Django 4.2.8 on 2024-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, verbose_name='urun adi')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='urun fiyati')),
                ('p_information', models.TextField(verbose_name='urun detayi')),
            ],
        ),
        migrations.CreateModel(
            name='Season_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=50, unique=True, verbose_name='Mevsim adi')),
            ],
        ),
        migrations.CreateModel(
            name='Size_species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_names', models.CharField(max_length=50, unique=True, verbose_name='Beden cesitleri')),
            ],
        ),
    ]
