# Generated by Django 4.2.8 on 2024-03-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_products_season_category_size_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=50, unique=True, verbose_name='Ozel durum')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='p_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category', verbose_name='urun kategorisi'),
        ),
        migrations.AddField(
            model_name='products',
            name='p_img',
            field=models.ImageField(max_length=300, null=True, upload_to='', verbose_name='urun resmi'),
        ),
        migrations.AddField(
            model_name='products',
            name='p_season_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.season_category', verbose_name='urun mevsimi'),
        ),
        migrations.AddField(
            model_name='products',
            name='p_sizes',
            field=models.ManyToManyField(null=True, to='mainApp.size_species', verbose_name='urun bedenleri'),
        ),
        migrations.AddField(
            model_name='products',
            name='p_special_status',
            field=models.ManyToManyField(blank=True, null=True, to='mainApp.specialstatus', verbose_name='ürün özel durumları'),
        ),
    ]
