# Generated by Django 4.2.8 on 2024-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_products_p_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_names', models.CharField(max_length=50, unique=True, verbose_name='Urun Markasi')),
            ],
        ),
    ]
