# Generated by Django 4.2.8 on 2024-03-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.brands', verbose_name='urun markasi'),
        ),
    ]
