# Generated by Django 4.2.8 on 2024-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_p_img_products_p_img_1_products_p_img_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_img_2',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='urun resmi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_img_3',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='urun resmi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_img_4',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='', verbose_name='urun resmi'),
        ),
    ]
