# Generated by Django 4.2.8 on 2024-03-23 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sehir')),
                ('profile_img', models.ImageField(default='profile_img/default/avatar.png', upload_to=userApp.models.profile_img_directory, verbose_name='profil_resmi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_table')),
            ],
        ),
    ]
